# Generated by Django 6.0.2 on 2026-02-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('matter_type', models.CharField(choices=[('litigation', 'Litigation'), ('compliance', 'Compliance'), ('investigation', 'Investigation'), ('transaction', 'Transaction'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attorneys', models.ManyToManyField(blank=True, related_name='legal_matters_as_attorney', to='stakeholders.stakeholder')),
                ('related_properties', models.ManyToManyField(blank=True, related_name='legal_matters', to='assets.realestate')),
                ('related_stakeholders', models.ManyToManyField(blank=True, related_name='legal_matters', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(blank=True, max_length=100)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='legal.legalmatter')),
            ],
            options={
                'verbose_name_plural': 'Evidence',
                'ordering': ['-date_obtained'],
            },
        ),
    ]
