# Generated by Django 6.0.2 on 2026-02-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalmatter',
            name='judgment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='next_hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
