from io import BytesIO

from django.http import HttpResponse
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _get_styles():
    """Return custom styles for PDF reports."""
    base = getSampleStyleSheet()
    base.add(ParagraphStyle(
        "SectionHead",
        parent=base["Heading2"],
        fontSize=12,
        spaceBefore=14,
        spaceAfter=6,
        borderWidth=0,
        borderPadding=0,
        borderColor=colors.grey,
    ))
    base.add(ParagraphStyle(
        "InfoLabel",
        parent=base["Normal"],
        fontSize=9,
        textColor=colors.grey,
    ))
    base.add(ParagraphStyle(
        "InfoValue",
        parent=base["Normal"],
        fontSize=10,
    ))
    base.add(ParagraphStyle(
        "Footer",
        parent=base["Normal"],
        fontSize=7,
        textColor=colors.grey,
        alignment=1,  # center
    ))
    return base


TABLE_STYLE = TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.93, 0.93, 0.93)),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.Color(0.3, 0.3, 0.3)),
    ("FONTSIZE", (0, 0), (-1, 0), 8),
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("FONTSIZE", (0, 1), (-1, -1), 9),
    ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
    ("TOPPADDING", (0, 1), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
    ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.grey),
    ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.Color(0.85, 0.85, 0.85)),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
])


def render_pdf(request, filename, title, subtitle="", sections=None):
    """Render a PDF report using reportlab.

    Args:
        request: Django HttpRequest
        filename: output filename (without .pdf extension)
        title: report title string
        subtitle: optional subtitle string
        sections: list of section dicts, each with:
            - "heading": section title (str)
            - "type": "info" | "table" | "text"
            - for "info": "rows" = list of (label, value) tuples
            - for "table": "headers" = list of str, "rows" = list of lists
            - for "text": "content" = str
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
    )
    styles = _get_styles()
    story = []

    # Title
    story.append(Paragraph(title, styles["Title"]))
    if subtitle:
        story.append(Paragraph(subtitle, styles["Normal"]))
    story.append(Spacer(1, 12))

    for section in (sections or []):
        heading = section.get("heading", "")
        if heading:
            story.append(Paragraph(heading, styles["SectionHead"]))

        stype = section.get("type", "text")

        if stype == "info":
            for label, value in section.get("rows", []):
                story.append(Paragraph(
                    f"<b>{label}:</b>  {value}",
                    styles["InfoValue"],
                ))
            story.append(Spacer(1, 6))

        elif stype == "table":
            headers = section.get("headers", [])
            rows = section.get("rows", [])
            if headers and rows:
                col_widths = section.get("col_widths", None)
                data = [headers] + rows
                t = Table(data, colWidths=col_widths, repeatRows=1)
                t.setStyle(TABLE_STYLE)
                story.append(t)
                story.append(Spacer(1, 8))

        elif stype == "text":
            content = section.get("content", "")
            if content:
                story.append(Paragraph(content, styles["Normal"]))
                story.append(Spacer(1, 6))

    # Footer
    story.append(Spacer(1, 20))
    now = timezone.now()
    story.append(Paragraph(
        f"Generated by Control Center — {now:%B %d, %Y %I:%M %p}",
        styles["Footer"],
    ))

    doc.build(story)

    response = HttpResponse(buf.getvalue(), content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{filename}.pdf"'
    return response
