# Generated by Django 6.0.2 on 2026-02-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('borrower_description', models.CharField(blank=True, max_length=255)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('collateral', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted'), ('in_dispute', 'In Dispute')], default='active', max_length=20)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_lender', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('owned', 'Owned'), ('under_contract', 'Under Contract'), ('sold', 'Sold'), ('in_dispute', 'In Dispute')], default='owned', max_length=20)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Real estate',
                'ordering': ['name'],
            },
        ),
    ]
