# Generated by Django 6.0.2 on 2026-02-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='Password')),
                ('from_email', models.EmailField(default='noreply@blaine.local', max_length=254, verbose_name='From email')),
                ('admin_email', models.EmailField(default='admin@blaine.local', max_length=254, verbose_name='Admin email (recipient)')),
                ('notifications_enabled', models.BooleanField(default=False, verbose_name='Enable email notifications')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
