# Generated by Django 6.0.2 on 2026-02-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry_type', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('is_projected', models.BooleanField(default=False)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_entries', to='assets.loan')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_entries', to='assets.realestate')),
                ('related_stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_entries', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Cash flow entries',
                'ordering': ['-date'],
            },
        ),
    ]
