# Generated by Django 6.0.2 on 2026-02-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('legal', '0001_initial'),
        ('stakeholders', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('note_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('research', 'Research'), ('legal_update', 'Legal Update'), ('general', 'General')], default='general', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='notes_as_participant', to='stakeholders.stakeholder')),
                ('related_legal_matters', models.ManyToManyField(blank=True, related_name='notes', to='legal.legalmatter')),
                ('related_properties', models.ManyToManyField(blank=True, related_name='notes', to='assets.realestate')),
                ('related_stakeholders', models.ManyToManyField(blank=True, related_name='notes', to='stakeholders.stakeholder')),
                ('related_tasks', models.ManyToManyField(blank=True, related_name='notes', to='tasks.task')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.note')),
            ],
        ),
    ]
