# Generated by Django 6.0.2 on 2026-02-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('legal', '0001_initial'),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('task_type', models.CharField(choices=[('one_time', 'One-Time'), ('reference', 'Reference')], default='one_time', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_legal_matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='legal.legalmatter')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='assets.realestate')),
                ('related_stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_date', models.DateTimeField()),
                ('method', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('text', 'Text'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=10)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('notes_text', models.TextField(blank=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='stakeholders.stakeholder')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='tasks.task')),
            ],
            options={
                'ordering': ['-outreach_date'],
            },
        ),
    ]
